WebApp/WebApp/Models/AdModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class AdModel
    {
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Status")]
        public bool Active { get; set; } = true; // Default set is true.

        [Required]
        [Display(Name = "Typ ogłoszenia")]
        public string Type { get; set; }

        [Display(Name = "Path")]
        public string ImagePath { get; set; }

        [Required]
        [Display(Name = "Obszar")]
        public string Area { get; set; }

        [Required]
        [Display(Name = "Krótki opis")]
        [MaxLength(256)]
        public string ShortDescription { get; set; }

        [Required]
        [Display(Name = "Umiejętności")]
        public string Skills { get; set; }

        [Display(Name = "Linki")]
        public string Links { get; set; }

        [Display(Name = "Data dodania")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime AddingDate { get; set; } = DateTime.Now; // Default set is current date.

        // Set relation one-to-zero-or-one
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

WebApp/WebApp/Controllers/AdModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Repo.IRepo;
using Repo.Models;
using Repo.Models.Partial;

namespace WebApp.Controllers
{
    public class AdModelsController : Controller
    {
        private readonly IAd _ad;
        private readonly IGetForView _getForView;

        public AdModelsController(IAd ad, IGetForView getForView)
        {
            _ad = ad;
            _getForView = getForView;
        }

        // GET: AdModels/Index
        [Authorize]
        public ActionResult Index()
        {
            // Check if User has created Ad
            if (_getForView.CheckAdByUserId(User.Identity.GetUserId()))
            {
                return RedirectToAction("Index", "Home");
            }

            // Get values for dropdownlist and checkboxlist (Ad Type and Ad Categories)
            AdModel adModel = _getForView.AdViewModel();

            return View(adModel);
        }

        // POST: AdModels/Index
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Index([Bind(Include = "ImagePath,Area,ShortDescription,Skills,AdType,SelectedCategories")] AdModel adModel, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                // Post Ad and saving changes
                var result = _ad.CreateAd(adModel,
                                            image,
                                            User.Identity.GetUserId(),
                                            Server.MapPath("~/UsersImages"));

                if (result)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return View(adModel);
        }
    }
}

WebApp/WebApp/Views/AdModels/Index.cshtml
@using Repo.Models
@using Repo.Extensions
@using Repo.HtmlHelpers
@using Microsoft.AspNet.Identity
@model Repo.Models.AdModel

@{
    ViewBag.Title = "Ogłoszenie";
}

<h2>Witaj @User.Identity.GetFirstName()!</h2>

<hr />

@using (Html.BeginForm("Index", "AdModels", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Teraz stwórz swoje ogoszenie.</h4>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.AdType.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.DropDownListFor(m => m.AdType.Id, new SelectList(Model.Types, "Id", "Name"), new { @class = "form-control" })*@
            <select class="form-control" name="AdType.Id">
                @foreach(var item in Model.Types)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.AdType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AdCategories, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Helper.CheckBoxList(new SelectList(Model.AdCategories, "Id", "Name"), "SelectedCategories")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Image" />
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ShortDescription, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Skills, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Skills, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Skills, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-success btn-lg" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}